apiVersion: v1
kind: Service
metadata:
  labels:
    app: books-api
  name: books-api
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "44368"
    port: 44368
    targetPort: 44368
  selector:
    app: books-api
status:
  loadBalancer: {}
