apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: moreno93/jenkins_k8s
        imagePullPolicy: IfNotPresent
        name: jenkins
        ports:
        - containerPort: 8080
        - containerPort: 50000
        resources: {}
      restartPolicy: Always
status: {}
