apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  type: NodePort
  ports:
  - name: "8080"
    nodePort: 31444
    port: 8080
    targetPort: 8080
  - name: "50000"
    nodePort: 31445
    port: 50000
    targetPort: 50000
  selector:
    app: jenkins
status:
  loadBalancer: {}
